"""
cli.py - Wave command-line entry point.

Usage:
    rpk-wave run   <wave_file> [--no-tui] [--workers N] [--tui-profile PROFILE]
    rpk-wave init  <name> [--profile PROFILE] [--force]
    rpk-wave export-docs <dir> [--force]
"""

from __future__ import annotations

import sys
import shutil
import importlib.resources as _res
from pathlib import Path
from string import Template

import click

from rpkbin.wave.runner import run
from rpkbin.wave.session import TUI_PROFILE_NAMES


# ---------------------------------------------------------------------------
# Wave file template used by `rpk-wave init`
# ---------------------------------------------------------------------------

_WAVE_TEMPLATE = Template('''\
"""
$name.wave.py - Wave batch script
Generated by: rpk-wave init $name

Run with: rpk-wave run $name.wave.py
"""

from __future__ import annotations

from rpkbin.wave import CmdJob, session
$imports

# =====
# Session
session.configure(max_workers=4)
session.configure_tui(dashboard_columns=[
    "no", "name", "status", "elapsed",
$dashboard_data_columns
    "exit_code",
])
$parser
$hooks
# =====
# Jobs
job = CmdJob(
    "hello",
    $command,
    tags={"demo"},
)
$attach
session.add(job)
$pty
''')


_PARSER_TEMPLATE = '''
# =====
# Parser (optional)
# Parsers extract structured data from job stdout line-by-line.
# The returned dict is merged into the job's parsed_data.
#
# Stateless: extract named regex groups directly
# from rpkbin.wave import RegexParser
# job.add_parser(RegexParser(r"PROGRESS=(?P<progress>[\\d.]+)"))
#
# Stateful: maintain memory across lines
# from rpkbin.wave import StatefulParser
# job.add_parser(StatefulParser(
#     r"(?P<warning>WARNING):",
#     on_match=lambda m, mem: {"count": mem.get("count", 0) + 1},
#     to_data=lambda m, mem: {"warning_count": str(mem["count"])},
# ))
#
# Advanced: plain function (full control)
# def my_parser(line: str) -> dict:
#     if line.startswith("RESULT:"):
#         return {"result": line.split(":", 1)[1].strip()}
#     return {}
# job.add_parser(my_parser)
'''


_MEMORY_PARSER_TEMPLATE = '''
# =====
# Stateful Parser Helpers
# Used by StatefulParser to maintain memory across log lines.
# E.g. captures STEP and merges it with subsequent RESULT.
def on_step_or_result_match(match_data: dict[str, str], memory: dict) -> dict:
    if "step" in match_data:
        return {"last_step": match_data["step"]}
    return {}


def step_or_result_to_data(match_data: dict[str, str], memory: dict) -> dict:
    if "step" in match_data:
        return {"step": match_data["step"]}
    if "result" in match_data:
        return {
            "result": match_data["result"],
            "last_step": memory.get("last_step", ""),
        }
    return {}
'''


_HOOK_TEMPLATE = '''
# =====
# Hook
def announce_done(job, ctx):
    """Lightweight job-local reaction when this job completes."""
    job.emit("done", f"{job.name} finished")
'''


_PTY_TEMPLATE = '''

# =====
# PTY Job Example
# Use PtyJob for interactive programs that need a real terminal.
# PtyCmdJob is the full class name; PtyJob is the short alias.
# Keep this disabled by default so this file also runs on Windows.
#
# if os.name == "posix":
#     interactive = PtyJob("interactive", "python3 -i")
#     session.add(interactive)
#
# In the TUI or headless REPL, send Ctrl-C without stopping Wave itself:
#   send-key interactive ctrl-c
'''


_INIT_PROFILES = ("minimal", "parser", "full", "pty")
_INIT_PROFILE_BLOCKS = {
    "minimal": (),
    "parser": ("parser",),
    "full": ("parser", "memory-parser", "hooks"),
    "pty": ("pty",),
}


def _render_wave_template(name: str, profile: str) -> str:
    try:
        blocks = _INIT_PROFILE_BLOCKS[profile]
    except KeyError as exc:
        allowed = ", ".join(_INIT_PROFILES)
        raise ValueError(f"Unknown init profile {profile!r}. Use one of: {allowed}") from exc
    block_set = set(blocks)
    parser_blocks = []
    attach_lines = []
    
    imports = []
    if "parser" in block_set:
        imports.append("RegexParser")
        parser_blocks.append(_PARSER_TEMPLATE)
        attach_lines.append("job.add_parser(RegexParser(r\"RESULT=(?P<result>\\\\w+)\"))")
    if "memory-parser" in block_set:
        imports.append("StatefulParser")
        parser_blocks.append(_MEMORY_PARSER_TEMPLATE)
        attach_lines.append(
            "job.add_parser(StatefulParser(\n"
            "    r\"(?:STEP=(?P<step>\\\\w+)|RESULT=(?P<result>\\\\w+))\",\n"
            "    on_match=on_step_or_result_match,\n"
            "    to_data=step_or_result_to_data,\n"
            "))"
        )

    hooks = _HOOK_TEMPLATE if "hooks" in block_set else ""
    if hooks:
        attach_lines.append("job.add_hook(Hook(Hook.on_done(), announce_done))")
    pty = _PTY_TEMPLATE if "pty" in block_set else ""
    has_parser = bool(parser_blocks)

    if pty:
        imports.append("os")
    if hooks:
        imports.append("Hook")
    if pty:
        imports.append("PtyJob")
    import_suffix = ""
    if imports:
        stdlib_imports = [item for item in imports if item == "os"]
        wave_imports = [item for item in imports if item != "os"]
        lines = []
        if stdlib_imports:
            lines.append("import os")
        if wave_imports:
            lines.append(f"from rpkbin.wave import {', '.join(wave_imports)}")
        import_suffix = "\n".join(lines)

    return _WAVE_TEMPLATE.substitute(
        name=name,
        imports=import_suffix,
        dashboard_data_columns='    {"label": "Result", "data": "result"},' if has_parser else "",
        command=repr(
            'python -c "print(\'STEP=compile\'); print(\'RESULT=pass\')"'
            if has_parser
            else 'python -c "print(\'Hello from Wave\')"'
        ),
        parser="".join(parser_blocks),
        hooks=hooks,
        attach="\n".join(attach_lines),
        pty=pty,
    )


@click.group()
def main() -> None:
    """Wave - A lightweight workflow layer for scheduling, executing, and monitoring batch jobs.

    Wave executes shell commands, pseudo-terminal (PTY) processes, and Python functions
    in a batch runner. It supports log parsers, reactive hooks, and resource/concurrency
    constraints. Active jobs can be monitored via a live interactive full-screen dashboard TUI
    (default) or controlled through a headless REPL environment.
    """
    pass


@main.command("run")
@click.argument("wave_file", type=click.Path(exists=True, dir_okay=False))
@click.option(
    "--no-tui",
    is_flag=True,
    default=False,
    help="CI/headless mode: execute the batch without launching the full-screen TUI.",
)
@click.option(
    "--workers",
    type=click.IntRange(min=1),
    default=None,
    help="Override the maximum concurrent workers configured in the wave file.",
)
@click.option(
    "--perf",
    is_flag=True,
    default=False,
    help="Collect and print lightweight performance and TUI refresh diagnostics on exit.",
)
@click.option(
    "--tui-profile",
    type=click.Choice(TUI_PROFILE_NAMES),
    default=None,
    help="Coarse performance profile (lite/normal/heavy) to scale TUI refresh rates and tail limits.",
)
def cmd_run(
    wave_file: str,
    no_tui: bool,
    workers: int | None,
    perf: bool,
    tui_profile: str | None,
) -> None:
    """Load WAVE_FILE and run the job batch.

    This command loads a declarative Python wave file, schedules all registered
    jobs, and executes them according to their resource limits,
    priorities, and hooks.
    
    By default, it launches a live interactive full-screen dashboard TUI.
    In non-interactive terminals or when --no-tui is passed, it runs headless.

    Examples:

      rpk-wave run my_flow.py

      rpk-wave run my_flow.py --no-tui --workers 4
    """
    raise SystemExit(run(wave_file, no_tui=no_tui, workers=workers, perf=perf, tui_profile=tui_profile))


@main.command("init")
@click.argument("name")
@click.option(
    "--force", "-f",
    is_flag=True,
    default=False,
    help="Overwrite the file if it already exists.",
)
@click.option(
    "--profile",
    type=click.Choice(_INIT_PROFILES),
    default="minimal",
    show_default=True,
    help=(
        "Starter template profile. "
        "minimal: basic setup with one job; "
        "parser: adds a stateless RegexParser; "
        "full: adds stateful parser and hooks; "
        "pty: adds POSIX PtyJob."
    ),
)
def cmd_init(name: str, force: bool, profile: str) -> None:
    """Generate a starter wave file named NAME.wave.py.

    This generates a declarative template python script that configures a Wave
    session and registers starter jobs, which can then be extended and run.

    Examples:

      rpk-wave init hello

      rpk-wave init hello --profile parser
    """
    # Strip .wave.py / .py suffix if the user accidentally included it
    stem = name
    for suffix in (".wave.py", ".py"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]

    out = Path(f"{stem}.wave.py")
    if out.exists() and not force:
        click.echo(
            f"[Wave] {out} already exists. Use --force to overwrite.",
            err=True,
        )
        raise SystemExit(1)

    content = _render_wave_template(stem, profile)
    out.write_text(content, encoding="utf-8")
    click.echo(f"[Wave] Created {out}")
    click.echo(f"       Edit the file, then run:  rpk-wave run {out}")



# ---------------------------------------------------------------------------
# Docs export helper
# ---------------------------------------------------------------------------


def _find_wave_docs_src() -> "Path | None":
    """Find the wave-specific docs directory shipped with the package.

    Returns the ``docs/wave`` subdirectory relative to the repository root,
    or ``None`` when the docs tree cannot be located.
    """
    pkg_root = Path(__file__).resolve().parent.parent
    candidates = [
        pkg_root / "docs" / "wave",
        pkg_root.parent / "docs" / "wave",
    ]
    return next((d for d in candidates if d.is_dir()), None)


@main.command("export-docs")
@click.argument("dest", type=click.Path())
@click.option(
    "--force", "-f",
    is_flag=True,
    default=False,
    help="Overwrite the destination directory even if it already contains files.",
)
def cmd_export_docs(dest: str, force: bool) -> None:
    """Export Wave Markdown documentation to the DEST directory.

    Creates DEST if it does not exist. Copies wave.md (English) and wave_zh.md
    (Traditional Chinese) into the 'wave' subdirectory inside DEST.
    Refuses to write when destination already contains files unless --force is given.

    Examples:

      rpk-wave export-docs ./docs

      rpk-wave export-docs ./docs --force
    """
    dest_path = Path(dest)

    docs_src = _find_wave_docs_src()
    if docs_src is None:
        click.echo(
            "[Wave] Cannot find the wave docs directory in the installed package.",
            err=True,
        )
        raise SystemExit(1)

    # Destination: <dest>/wave/
    wave_dest = dest_path / "wave"

    if wave_dest.exists() and any(wave_dest.iterdir()) and not force:
        click.echo(
            f"[Wave] {wave_dest} already has content. Use --force to overwrite.",
            err=True,
        )
        raise SystemExit(1)

    dest_path.mkdir(parents=True, exist_ok=True)
    shutil.copytree(str(docs_src), str(wave_dest), dirs_exist_ok=True)

    click.echo(f"[Wave] Docs exported to: {dest_path.resolve()}")
    for fname in ("wave.md", "wave_zh.md"):
        entry = wave_dest / fname
        if entry.exists():
            rel = entry.relative_to(dest_path)
            click.echo(f"       Main entry:  {rel}")


if __name__ == "__main__":
    main()
