"""
cli.py - Wave command-line entry point.

Usage:
    rpk-wave run   <wave_file> [--no-tui] [--workers N]
    rpk-wave init  <name>
    rpk-wave docs
"""

from __future__ import annotations

import sys
import webbrowser
import importlib.resources as _res
from pathlib import Path

import click

from rpkbin.wave.runner import run


# ---------------------------------------------------------------------------
# Wave file template used by `rpk-wave init`
# ---------------------------------------------------------------------------

_WAVE_TEMPLATE = '''\
"""
{name}.wave.py  -  Wave batch script
Generated by: rpk-wave init {name}

Run with:  rpk-wave run {name}.wave.py
"""

from rpkbin.wave.session import session

# ===========================================================================
# Session configuration
# ===========================================================================
# max_workers: how many jobs run concurrently (default 4)
# log_buffer:  per-job in-memory log lines retained (default 10000)
session.configure(
    max_workers=4,
    # log_buffer=10000,
)

# TUI display options (ignored in --no-tui mode)
# dashboard_columns: list of column dicts with keys "key", "label", "width"
#   Built-in keys: name, status, elapsed, progress, exit_code
#   Parsed-data keys: "data:<your_key>"
# session.configure_tui(
#     dashboard_columns=[
#         {{"key": "name",    "label": "Job",     "width": 30}},
#         {{"key": "status",  "label": "Status",  "width": 12}},
#         {{"key": "elapsed", "label": "Elapsed", "width": 10}},
#     ]
# )

# ===========================================================================
# Parser (optional)
# ===========================================================================
# Parsers extract structured data from job stdout line-by-line.
# The returned dict is merged into the job\'s parsed_data.
#
# def make_parser():
#     def parser(line: str) -> dict | None:
#         if line.startswith("RESULT:"):
#             return {"result": line.split(":", 1)[1].strip()}
#         return None
#     return parser

# ===========================================================================
# Jobs
# ===========================================================================
# Add jobs to the session.  The simplest form is CmdJob.
from rpkbin.wave.jobs import CmdJob

# Example 1: run a shell command
session.add(CmdJob(
    name="hello",
    cmd=["echo", "Hello, Wave!"],
    # tags=["group-a"],          # used for stop --group / cancel --group
    # parser=make_parser(),      # attach a parser for structured output
    # on_done=lambda job: None,  # hook called when job finishes
))

# Example 2: multiple jobs (common pattern)
# for i in range(5):
#     session.add(CmdJob(
#         name=f"task-{{i}}",
#         cmd=["python", "my_script.py", "--index", str(i)],
#     ))
'''


@click.group()
def main() -> None:
    """Wave - lightweight job batch runner with real-time monitoring."""
    pass


@main.command("run")
@click.argument("wave_file", type=click.Path(exists=True, dir_okay=False))
@click.option(
    "--no-tui",
    is_flag=True,
    default=False,
    help="CI mode: run headless without opening the TUI.",
)
@click.option(
    "--workers",
    type=click.IntRange(min=1),
    default=None,
    help="Override max_workers set in the wave file.",
)
@click.option(
    "--perf",
    is_flag=True,
    default=False,
    help="Enable lightweight perf/debug counters.",
)
def cmd_run(wave_file: str, no_tui: bool, workers: int | None, perf: bool) -> None:
    """Load WAVE_FILE and run the job batch."""
    raise SystemExit(run(wave_file, no_tui=no_tui, workers=workers, perf=perf))


@main.command("init")
@click.argument("name")
@click.option(
    "--force", "-f",
    is_flag=True,
    default=False,
    help="Overwrite existing file.",
)
def cmd_init(name: str, force: bool) -> None:
    """Generate a starter wave file named NAME.wave.py.

    Example:
        rpk-wave init hello      # creates hello.wave.py
    """
    # Strip .wave.py / .py suffix if the user accidentally included it
    stem = name
    for suffix in (".wave.py", ".py"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]

    out = Path(f"{stem}.wave.py")
    if out.exists() and not force:
        click.echo(
            f"[Wave] {out} already exists. Use --force to overwrite.",
            err=True,
        )
        raise SystemExit(1)

    content = _WAVE_TEMPLATE.format(name=stem)
    out.write_text(content, encoding="utf-8")
    click.echo(f"[Wave] Created {out}")
    click.echo(f"       Edit the file, then run:  rpk-wave run {out}")


@main.command("docs")
def cmd_docs() -> None:
    """Show the location of Wave documentation and open it in a browser."""
    # Try to find docs shipped with the package
    try:
        pkg_root = Path(__file__).resolve().parent.parent
        candidates = [
            pkg_root / "docs",
            pkg_root.parent / "docs",
        ]
        docs_dir = next((d for d in candidates if d.is_dir()), None)
    except Exception:
        docs_dir = None

    if docs_dir is not None:
        index = docs_dir / "index.html"
        click.echo(f"[Wave] Docs directory: {docs_dir}")
        if index.exists():
            click.echo(f"       Opening: {index}")
            webbrowser.open(index.as_uri())
        else:
            click.echo("       (No index.html found; browse the directory manually.)")
    else:
        click.echo("[Wave] No local docs directory found.")
        click.echo("       Online docs: https://github.com/your-org/rpkbin (update this URL)")
        click.echo("       To see the built-in help inside the TUI: press F4 or type 'help'")


if __name__ == "__main__":
    main()

