"""Target-neutral debugger contracts and a small DAP server."""

from .dap import DAPProtocolError, DAPServer, DAPTransport, serve_stdio
from .model import (
    AddressSpace,
    BreakpointResult,
    DebugCapabilities,
    DebugLocation,
    DebugScope,
    DebugSessionFactory,
    DebugTarget,
    DebugVariable,
    ExecutionContext,
    InstructionBreakpoint,
    SourceBreakpoint,
    SourceBreakpointResult,
    SourceLocation,
    StopReason,
    StopResult,
    SupportsAttach,
    SupportsClose,
    SupportsReverseStep,
    SupportsSourceBreakpoints,
)

__all__ = [
    "AddressSpace",
    "BreakpointResult",
    "DAPProtocolError",
    "DAPServer",
    "DAPTransport",
    "DebugCapabilities",
    "DebugLocation",
    "DebugScope",
    "DebugSessionFactory",
    "DebugTarget",
    "DebugVariable",
    "ExecutionContext",
    "InstructionBreakpoint",
    "SourceBreakpoint",
    "SourceBreakpointResult",
    "SourceLocation",
    "StopReason",
    "StopResult",
    "SupportsAttach",
    "SupportsClose",
    "SupportsReverseStep",
    "SupportsSourceBreakpoints",
    "serve_stdio",
]
